python -m torch.distributed.launch --nproc_per_node=8 reranker_train.py \
  --output_dir reranker_msmarco \
  --model_name_or_path bert-base-uncased \
  --save_steps 20000 \
  --dataset_name Tevatron/msmarco-passage \
  --fp16 \
  --per_device_train_batch_size 2 \
  --train_n_passages 16 \
  --learning_rate 5e-6 \
  --q_max_len 16 \
  --p_max_len 128 \
  --num_train_epochs 5 \
  --logging_steps 500 \
  --overwrite_output_dir \
  --dataset_proc_num 96